spring:
  profiles:
    default: local

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

---
spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: []
